name          'bashtoni-phpapc'
version       '1.0.0'
source        'UNKNOWN'
author        'Bashton Ltd'
license       'Apache License, Version 2.0'
summary       'Install and configure PHP APC'
description   'Simple module to install PHP and APC module'
project_page  'https://github.com/BashtonLtd/puppet-phpapc'

dependency 'puppetlabs/stdlib', '>= 3.2.0'
